#pragma once

#include <cstdint>
#include <memory>
#include <vector>

#include "horizon/math/Vec3.h"
#include "horizon/topology/TopologyID.h"

namespace hz::geo {
class NurbsCurve;
class NurbsSurface;
}  // namespace hz::geo

namespace hz::topo {

struct HalfEdge;
struct Edge;
struct Face;
struct Wire;
struct Shell;
class Solid;

/// A vertex in the B-Rep — stores a 3D position and one outgoing half-edge.
struct Vertex {
    uint32_t id = 0;
    TopologyID topoId;
    math::Vec3 point;
    HalfEdge* halfEdge = nullptr;  ///< One outgoing half-edge.
};

/// A directed edge bounding one face.  The twin half-edge bounds the adjacent face.
struct HalfEdge {
    uint32_t id = 0;
    Vertex* origin = nullptr;
    HalfEdge* twin = nullptr;
    HalfEdge* next = nullptr;
    HalfEdge* prev = nullptr;
    Edge* edge = nullptr;
    Face* face = nullptr;
};

/// A topological edge shared by two half-edges (one in each direction).
struct Edge {
    uint32_t id = 0;
    TopologyID topoId;
    HalfEdge* halfEdge = nullptr;  ///< One of the two half-edges.
    std::shared_ptr<geo::NurbsCurve> curve;

    /// The ideal curve this edge approximates, when it was generated by
    /// faceting one (a chord of a circular rim, say).
    ///
    /// This is NOT the edge's geometry — `curve` is, and it runs between the
    /// edge's own vertices.  This records what the chord stands in for, so
    /// feature recognition (radial dimensions, analytic export, refitting)
    /// can recover the design intent a facet discards.  Null when the edge is
    /// its own exact geometry.
    std::shared_ptr<geo::NurbsCurve> analyticCurve;
};

/// A closed loop of half-edges forming a face boundary.
struct Wire {
    uint32_t id = 0;
    HalfEdge* halfEdge = nullptr;  ///< Any half-edge in the loop.
};

/// A planar or curved region bounded by one outer wire and zero or more inner wires (holes).
struct Face {
    uint32_t id = 0;
    TopologyID topoId;
    Wire* outerLoop = nullptr;
    std::vector<Wire*> innerLoops;
    Shell* shell = nullptr;

    /// The face's carrier: the surface its boundary loop actually lies on.
    std::shared_ptr<geo::NurbsSurface> surface;

    /// The ideal surface this face approximates, when it was generated by
    /// faceting one — the cylinder a lateral facet came from, say.
    ///
    /// This is NOT the carrier.  Curved primitives are faceted at
    /// construction so that the kernel's loop-based evaluation (Booleans,
    /// classification, mass properties) matches what is displayed and
    /// exported; binding the curved surface to a planar facet would put the
    /// two back out of step.  Recording it separately keeps the design intent
    /// available to feature recognition — a single facet can still answer
    /// "I am part of a cylinder of radius r about this axis", which is what
    /// assembly mates and radial dimensions need from one pick.
    std::shared_ptr<geo::NurbsSurface> analyticSurface;
};

/// A connected set of faces forming a closed (or open) skin.
struct Shell {
    uint32_t id = 0;
    std::vector<Face*> faces;
    Solid* solid = nullptr;  ///< Owning solid.
};

}  // namespace hz::topo
