# CPack / NSIS installer configuration
set(CPACK_GENERATOR "NSIS")
set(CPACK_PACKAGE_NAME "HorizonCAD")
set(CPACK_PACKAGE_VENDOR "Horizon CAD Project")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Open-source parametric 2D/3D CAD")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_INSTALL_DIRECTORY "HorizonCAD")
set(CPACK_NSIS_DISPLAY_NAME "Horizon CAD ${PROJECT_VERSION}")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")

# Desktop shortcut
set(CPACK_NSIS_CREATE_ICONS_EXTRA
    "CreateShortCut '$DESKTOP\\\\Horizon CAD.lnk' '$INSTDIR\\\\bin\\\\horizon.exe'"
)
set(CPACK_NSIS_DELETE_ICONS_EXTRA
    "Delete '$DESKTOP\\\\Horizon CAD.lnk'"
)
