# Version information
set(HZ_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(HZ_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(HZ_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(HZ_VERSION_STRING "${HZ_VERSION_MAJOR}.${HZ_VERSION_MINOR}.${HZ_VERSION_PATCH}")
