# Writes horizon/Revision.h: the source revision the build was made from.
# Run at configure time and again on every build, but the file is rewritten
# only when the revision changes, so nothing recompiles for nothing.
#   cmake -DGIT=<git> -DSRC=<source dir> -DOUT=<header> -P WriteRevision.cmake
set(revision "unknown")
if(GIT)
    execute_process(
        COMMAND ${GIT} rev-parse --short HEAD
        WORKING_DIRECTORY ${SRC}
        OUTPUT_VARIABLE _hz_revision
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _hz_result)
    if(_hz_result EQUAL 0 AND _hz_revision)
        set(revision "${_hz_revision}")
    endif()
endif()
set(content "#pragma once\n\n// Generated by cmake/WriteRevision.cmake: the source revision of this build.\n\nnamespace hz::version {\n\ninline constexpr const char* kRevision = \"${revision}\";\n\n}  // namespace hz::version\n")
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${OUT}" "${content}")
endif()
